language: go
go:
  - "1.11"
  - "1.11.x"
env:
  - GO111MODULE=on
notifications:
  email:
    recipients:
      - 1156143589@qq.com
    on_success: change # default: change
    on_failure: always # default: always

before_install:
  - go test -cpu=1,2,4 -v -tags integration ./...
  - go vet $(go list ./... | grep -v /vendor/)

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - echo "Hello getui-sdk-go"


after_success:
  - docker build -t wuxiaoshen/getui-sdk-go:latest .
  - docker push wuxiaoshen/getui-sdk-go:latest

